name: device_preview
version: 0.6.2-beta
description: Approximate how your Flutter app looks and performs on another device.
homepage: https://github.com/aloisdeniel/flutter_device_preview

environment:
  sdk: '>=2.7.0 <3.0.0' 

dependencies:
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^5.0.0
  path_provider: ^2.0.2
  device_frame: ^0.4.2
  font_awesome_flutter: ^9.0.0
  http: ^0.13.3
  freezed_annotation:
  json_annotation:
  meta: ^1.3.0
  shared_preferences: ^2.0.6
  pedantic: ^1.11.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter 
  build_runner: ^2.0.4
  freezed: ^0.14.2
  json_serializable: ^4.1.3
  analyzer: ^1.7.1

dependency_overrides:
  analyzer: ^1.7.1
  json_annotation:
  convert:
  xml: